### ISSUE TITLE
Configuration > Security > Files > max upload size - settings missing

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#11]
Hi guys,
a Configuration > Security > Files > **max upload size** - setting is missing to set a value lower than the server configuration that should applied:

- on Email **attachments**
- on all the Email Editor attachments like the **Image** content block:

**Comment by JeremyAcyba** [comment]
Please use [the feature requests section](https://www.acymailing.com/feature-requests/) of our site for feature requests.

**Comment by joomleb** [comment]
Hi @JeremyAcyba 
feature request [added here]([feature request](https://app.productstash.io/acymailing?idea=60233341fd1817002d4f2886) <), thanks!
