### ISSUE TITLE
Insert Dynamic Text > Readonline tag - setting to add / remove &tmpl=component

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#12]
Hi guys,
Please, restore the settings of the old AcyMailing 5 plugin as soon as possible to view the Email online with or without the template &tmpl=component

Insert Dynamic Text > Readonline tag: a setting to add / remove &tmpl=component OR a double Readonline tag choose (with or without template)

PS - The same setting would be good for the Unsubscribe page and the Subscription one

**Comment by JeremyAcyba** [comment]
Hello,

It's been a while, but it is now possible to show the online version in the site's template using a new option:

<img width="347" alt="option" src="https://user-images.githubusercontent.com/9281637/196909516-cad96670-7a81-465f-8a5a-2afa6e7b26ec.png">
