### ISSUE TITLE
Add-ons > HikaShop plugin > Settings > Front-end access - BUG

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#14]
Hi guys, 
as you done for all the others plugins, into the "Add-ons > HikaShop plugin > Settings > Front-end access" the "**Display the current user’s elements**" option is missing - [here an image](https://photos.app.goo.gl/c7ybiPXLUMGtW3J69) - if confirmed, this is a BUG issue: AcyMailing feature "is not running as expected"

That should follow the [HikaMarket Vendor,](https://www.hikashop.com/support/documentation/142-multivendor-presentation.html) setting when the HikaMarket (the HikaShop addon) is installed. Practically, it is the substitute of the "Product Created by", the "Product owner", who can manage the Products.

the information it is saved into the tables:
_hikashop_product > product_vendor_id
_hikamarket_vendor_user > vendor_id / user_id

PS - You have the full access into my Test2 site if you need to test it with both yet installed

**Comment by joomleb** [comment]
HI Alexandre,
Are you sure this is an "enhancement" ?
With AcyMailing 6.13 release the "Setting" options feature has been added to all the plugins.
To all the plugins the "Front-end access > Display the current user’s elements" option has been added.
I suppose and believe this is just a big missing because HikaShop manage it (the permissions on the ownership of the products) through its own HikaMarket addon. 
If confirmed, it should be just a little BUG Fix

**Comment by AlexandreAcyba** [comment]
Hi, 

That's not a bug as we don't have any integration with HikaMarket. 

It runs as expected based on the HikaShop plugin. 

If we had an HikaMarket integration then you would have seen "Display the current user’s elements" option.
That means we need to think about adding HikaMarket integration. 

It has been added into our TODO list. Thanks for suggesting it ;-)
