### ISSUE TITLE
Add-ons > plugins > Settings: Icon & Title - request

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#15]
Hi guys, 
would be useful to add the "Icon" & "Title" settings for the plugins to be able to show a custom Icon and Title in the Frontend. This is really useful for us to manage well our customers.
I mean, for example: for our customers "DPCalendar" do not mean nothing, while would be good to show "Events" as title in the Frontend - [here an image](https://photos.app.goo.gl/9dht5izRb6ZYKJXR6)

PS - in case this request is discarded, Please, Can you suggest the correct method to change them manually? And add it to the documentation

**Comment by AlexandreAcyba** [comment]
Hi, 

You can change the image it using this path : administrator/components/com_acym/dynamics/<plugin>/icon.png
Regarding the text you can change it from the file : administrator/components/com_acym/dynamics/<plugin>/plugin.php
`$this->pluginDescription->name = 'WooCommerce';`

However this will be overriden everytime AcyMailing is updated as it's kind of modifying AcyMailing core files

**Comment by joomleb** [comment]
Hi Alexandre, 
many thanks to your suggestions I made manual modifications to them, hoping for an update in the next releases. 
Anyway, as far as I see and I can understand (I'm writing also for users that can be interested):

**Titles** - managing them through a simple language string, like you are doing for the "pre-installed add-ons" as for ex. "Articles", it will solve this request:
- from: $this->pluginDescription->name = 'DPCalendar';
- to: $this->pluginDescription->name = **acym_translation('ACYM_DPCALENDAR')**;
(the language string is just an example)

**Icons** - while the "pre-installed add-ons" plugin icons are loaded from Font Awesome (like for "Articles"), the others add-ons plugin icons are loaded from an icon image directory:
- $this->pluginDescription->icon = ACYM_DYNAMICS_URL.basename(__DIR__).'**/icon.svg**';
To have a "to select icon plugin" setting OR to don't replace the icon.svg during updates will solve the request.
PS - for sure will be good to have all the icons as .svg extension.
