### ISSUE TITLE
Mass Action creates copy of Email/Campaign

### ISSUE THREAD

**Issue by Rakeshmvd** [acyba/acymailing6#18]
When using mass action and adding an email to a campaign queue, a copy of the Email/campaign is being created.

So when using the add email to a queue a couple times, each time this action is being created a new  CAMPAIGNNAME_copy is being created in the choose capaign list.

**Comment by JeremyAcyba** [comment]
This is the intended behaviour. Once an email is selected, you can either let the _copy in its name or rename it.
This has been made to separate the original campaign and the one used in the automation in the statistics page.
