### ISSUE TITLE
Email Overrides - Extensions - request + Component Connector

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#31]
Hi guys, 
about the new Email Overrides feature, 

1 - we'd like to see asap these Extensions integrations, in order of importance:
- Solidres
- DPCalendar
- HikaShop + HikaMarket + HikaSubscription
- JFBConnect + Joocial by Extly
- Seblod
- (Akeeba Backup + Admin Tools)

2 - Then, on Acyba old feature requests section site there where a "Component Connector" propose / suggestion coding:
https://www.acyba.com/community/feature-requests/request/view/id-298.html
that I found too interesting to permit to developer to directly integrate AcyMailing, What became of that proposal?

**Comment by micker** [comment]
And flexicontent

**Comment by JeremyAcyba** [comment]
An integration for DPCalendar, HikaShop and Seblod have been added.

Please use [the feature requests section](https://www.acymailing.com/feature-requests/) of our site for the remaining feature requests.
