### ISSUE TITLE
Phone and Date custom fields - BUGs

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#47]
Hi guys, 
PHP 7.4.15 + Joomla 3.9.25 + AcyMailing 7.2.x + Subscription Form module > Custom Fields - [here an image](https://photos.app.goo.gl/JpGEFmmG978DqX3Y6)

**1** - Phone - it is shown on two lines  while
**Solution** - it should be shown inline by default

**2** - Date (Birthday) - with the day / months / year selectors the Label never can be shown "inside", so, if in the module I set "Display text mode: inside" the date custom field label disappear
**Solution** - use the joomla default calendar date icon selector

**Comment by Talrus-Thane** [comment]
This github repository has been created to let the community share their modifications but isn't used by the AcyMailing developers, the "Issues" menu is never checked by the team.

Please post bug reports on [our contact form](https://www.acymailing.com/support) and feature requests on [our dedicated page](https://www.acymailing.com/feature-requests).
