### ISSUE TITLE
Plugin & Triggers based on user actions - missings

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#5]
Hi guys, 
AcyMailing 6 has a very good internal plugins management for integrations to others 3d party Extensions.
Right now when you add a plugin, it add (let me say) Tags that permit to add them to the AcyMailing Emails. 
But, a really integration plugin should always add also Triggers property into Automations. Basically, for a portal management there are some basic Triggers for all Extensions that should be added by default.
Let me give you an example with my needs:

Automation > Information - **Trigger based on user actions**:
- On Buy something: Event booking by DPCalendar plugin - Reservation (Property or Experience) by Solidres plugin - Product by HikaShop (you yet added)
- On adding to Wish List (and on deleting): DPCalendar / Solidres (I'm waiting the plugin release) / HikaShop
- On User Birthday: (you yet added)

Only by adding the basic Triggers to the Automation a plugin we can say it has been developed and the extension integrated

**Comment by pinochico** [comment]
Because we don't want waiting for development acy, then we create own system plugins with own triggers, which we need:
- rd-e-tickets
- virtuemart (not all triggers what we need exist in this time in automation)
- greetings

In future we need plugins for Form2Content (tags and filters), then maybe I like this.

**Comment by ssnobben** [comment]
Any news or update?

**Comment by joomleb** [comment]
Hi guys, 
@ssnobben I added a "Plugins integrations: Email + Triggers + Emali Override and process /component connector" into the AcyMailing [Feature Requests](https://www.acymailing.com/feature-requests/) section, Please, vote it!

**Comment by ssnobben** [comment]
voted

**Comment by JeremyAcyba** [comment]
Please use the feature requests section of our site for feature requests :)
