### ISSUE TITLE
Users / Lists / Emails limits settings - missings

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#6]
Hi guys, 
I'm going to post this here as a "big missing" instead of a "feature request".
The AcyMailing 6 feature you wrote here: "[You can even think about reselling this newsletter system without letting them know you’re using AcyMailing to do it](https://blog.acymailing.com/news/acymailing-6-7-0-is-out-whats-new/)" it is one of the most important and till today are really big missings that prevent us from offering the use of the frontend to our customers.

To enable the Frontend User Management to our customers we should be able to set:
- **Users** - a way to limit the number of users per list (be careful to the import feature that has to check that setting during the import process) depending on Joomla user group
- **Lists** - a way to limit the lists number depending on Joomla user group
- **Emails** (Campaigns) - a way to limit the Emails (Newsletters) creation (per day / week / month) depending on Joomla user group

DPCalendar component found the simples and flexible solution:
--- to add the Users / Lists / Emails limits settings into configuration
--- to call them as "Options" in a tab into the Users / Lists / Emails Menu Items > here the limit setting should be lower than the one into configuration (if set)
In this way we'll can create Menu Items for specific user groups and with the specific limits.

Without these settings we cannot offer the promised Email service to our customers. A must.
Please, Can you add these settings for the upcoming next release ?

**Comment by JeremyAcyba** [comment]
Please use [the feature requests section](https://www.acymailing.com/feature-requests/) of our site for feature requests.

**Comment by joomleb** [comment]
Hi @JeremyAcyba 
feature request [added here](https://app.productstash.io/acymailing?idea=602372e3fd1817002d4f2c20), thanks
