### ISSUE TITLE
Issue running cronurl in crontab

### ISSUE THREAD

**Issue by rhliberman** [acyba/acymailing6#65]
Hi - We're running AcyMailing (paid version) on an Intranet server and cannot access AcyMailing in order use their cron service. I've added the cronurl to our server's crontab (Linux), but it does not work, It triggers, but does nothing.

*/15 * * * 1-5 curl -s "https://server/index.php?option=com_acymailing&ctrl=cron" > /data/logs/acymailing.log

Please tell me the correct settings to use in order to correctly run AcyMailing on a schedule.

Thanks!

**Comment by mihha** [comment]
HI,

please open a support ticket using contact form on Acyba site, just as I suggested in the forum topic 

We can't provide support here on the GitHub

Thank you for understanding!

**Comment by rhliberman** [comment]
Sorry

**Comment by JeremyAcyba** [comment]
In case anyone stumbles upon this thread, rhliberman found a solution before we could investigate.
I can see "com_acymailing" in the provided cron URL, which is the AcyMailing 5 extension, maybe it was this.
