### ISSUE TITLE
Unsubscribe page settings - missings

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing6#7]
Hi guys, 
PHP 7.3.20 + Joomla 3.9.20 + AcyMailing Enterprise 6.13.2
 - I built my “[Subscription page](https://test2.egulp.net/ajustes)” (Ajustes) using the AcyMailing subscription form Module + SP Page Builder and its Joomla Module addon. It is working fine with the logged in / logged out users.
 - On my Email Template I insert an Unsubscribe link Dynamic Text Tag.
 - Setting: Configuration > [Interfaces](https://docs.acymailing.com/setup/configuration/interface) > Unsubscribe page > Redirect to an unsubscribe page after the user clicks on an unsubscribe link:
 ---- **disabled**: when clicking on the unsubscribe tag link the user should be directed to the homepage and a Joomla system message should be shown with the unsubscribe confirmation message (it seems it has been fixed on last release). The user will be unsubscribed from the specific list from unsubscribe link. He won't be unsubscribed from all lists. What should happen in case I send the email to two Lists and the User is clicking on the Email Unsubscribe link is subscribed on both Lists ? Will he be canceled by both Lists? Anyway he will be cancelled only from the Lists related to that email, Am I right ?
 ---- **enabled**: when clicking on the unsubscribe tag link the user should be directed to the AcyMailing “Unsubscribe page” with &tmpl=component attached (without template). User will have an opportunity to select which newsletter lists he would like to be unsubscribed when he confirms the selection on the unsubscribe page.

Now,
- **1** - Would be good to have an Unsubscribe link option (asked more than one time on the forum): to don’t add template / to add the template > in AcyMailing 5 there was a [plugin option](https://docs.acymailing.com/v/old/integration-plugins/installed-with-acymailing/plugin-manage-subscription#parameters) to do it
- **2A** - In my case I simply would like to redirect the user to the “[Subscription page](https://test2.egulp.net/ajustes)” (Ajustes page) having back the AcyMailing subscription form Module running as an Unsubscribe page (recognizing the user as if he were logged in). Please, Why not to add an Unsubscription redirect URL field Setting in the configuration ?
- **2B** - If it is not possible and to create a Template Override unsub.php page [as described here](https://forum.acymailing.com/d/673-edit-design-the-unsubscribe-page/2) is the only solution. Please, Do you have a code Tip / Trick to add a simple redirect in the unsub.php to the wanted page ?

**Comment by JeremyAcyba** [comment]
1 - The website template option has been added.
 2A - You can insert a link to this page instead of the automated unsubscribe link.
2B - An option to specify a redirection link after unsubscribe is in the todo list but hasn't been upvoted enough in our feature requests page.
